 #DB
spring:
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoppingwiki
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        order_updates: true
        order_inserts: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 500
        show_sql: true
  data:
    web:
      pageable:
        default-page-size: 100
    redis:
      host: apn1-clean-grub-33520.upstash.io
      port: 33520
      password: a94dce6adebf438e89c1d79a0655a567
  thymeleaf:
    cache: true
  application:
    name: shoppingwiki
  rabbitmq:
    port: 5672
    password: tARJVmiTFLRvpHGU97UxZ8Jl8MrSGurb
    addresses: amqps://lbmvskfp:tARJVmiTFLRvpHGU97UxZ8Jl8MrSGurb@dingo.rmq.cloudamqp.com/lbmvskfp
  main:
    lazy-initialization: true
  devtools:
    add-properties: false
#logging
logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    org:
      hibernate:
        sql: debug
        type: trace
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG


server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: refresh , health , beans , busrefresh

#token:
#  expiration_time: 86400000
#  secret: 97F296E4586CDA219CF5A1F463B97394EAEFCDE349A6FF67E496C9EB5F
springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /shoppingwiki/v3/api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

token:
  expiration_time: 86400000
  secret: 97F296E4586CDA219CF5A1F463B97394EAEFCDE349A6FF67E496C9EB5F



